site_name: Embedded Event Logging
repo_url: https://github.com/RohitPatil555/embd_event_logging
repo_name: 'GitHub'
edit_uri: blob/main/docs/docs
use_directory_urls: false
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - c++
nav:
  - Home: index.md
  - Internal:
    - Intro: internal/index.md
    - Host To Device Interface: internal/host_to_device_interface.md
  - Other:
    - Requirement: static-reqs\/index.html
