site_name: Embedded Event Logging
use_directory_urls: true
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - c++
nav:
  - Home: index.md
  - Requirement: static-reqs\/index.html