name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file .devcontainer/Dockerfile --tag embd_event_log:$(git rev-parse --short=8 HEAD)
    - name: Execute CI
      run: docker run -v ${{ github.workspace }}:/workspaces embd_event_log:$(git rev-parse --short=8 HEAD) /workspaces/test_ci.sh
