name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get project detail
      run: |
        PROJECT_NAME="${{ github.event.repository.name }}"
        echo "The project name is: $PROJECT_NAME"
        # You can also set it as an environment variable for subsequent steps
        echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
        ls -lrt ${{ github.workspace }}

    - name: Build the Docker image
      run: docker build . --file .devcontainer/Dockerfile --tag evt_capture_lib:$(git rev-parse --short=8 HEAD)

    - name: Execute CI
      run: |
        mkdir -p artifacts
        chmod -R 666 artifacts
        docker run --rm -v $PWD/artifacts:/workspaces/artifacts \
            -v ${{ github.workspace }}:/workspaces \
            -e GITHUB_ACTIONS=true \
            -e PROJECT_PATH=/workspaces \
            evt_capture_lib:$(git rev-parse --short=8 HEAD) /workspaces/test_ci.sh --build-dir /tmp/build --artifacts
        sudo chmod -R 0777 artifacts/
        sudo chown -R $USER:$GROUP artifacts/

    - name: Upload docs artifact
      uses: actions/upload-artifact@v4
      with:
        name: site
        path: artifacts/docs_output/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download docs artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: site

      - name: Setup pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
